### ISSUE TITLE
Unable to login if LDAP server is gone

### ISSUE THREAD

**Issue by eloo** [schaal/ocreader#72] opened 2017-08-16 15:08 UTC
## Description of the issue
If Nextcloud is configured to use LDAP and this LDAP server is gone OCReader is unable to login also for local accounts.

## Expected behavior
Login/Fetch works for locale accounts no matter if the LDAP is there or gone

## Steps to reproduce
1. Active and configure LDAP in Nextcloud
2. Shutdown the LDAP server
3. Try to fetch articles

## Your Environment

* OCReader version: 0.36
* Nextcloud news version: 12.0.1
* Android version: 7.0.1

### Logcat
Currently no log available. Will update this if necessary

**Comment by schaal** [comment] 2017-08-18 04:38
Is there anything about this in your nextcloud log?
Does this also happen with other apps trying to login?

**Comment by schaal** [comment] 2017-08-25 15:17
I could reproduce this now on a test nextcloud instance. This is probably an upstream issue, which has to be solved on the server side, as this also occurs with other apps.

A workaround is to create an app password and use this to login.

**Comment by schaal** [comment] 2017-09-18 05:21
As this seems to be a nextcloud issue, will close this here

**Closed by schaal** 2017-09-18 05:21 UTC
Labels: bug
