### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by marcelklehr** [schaal/ocreader#35] opened 2017-01-08 00:06 UTC
## Description of the issue
I cannot log into nextcloud and get a 504 Gateway time-out instead.

## Expected behavior
I should be able to login.

## Steps to reproduce
1. Install OCReader
2. Input account info
3. press sign in

It might be relevant that I have 91 unread articles in the news app atm.

## Your Environment

* OCReader version: 0.26
* Nextcloud news version: Nextcloud 11, I haven't 
* Android version: 4.2
* Apache: TimeOut 300
* PHP: max_execution_time = 240

**Comment by schaal** [comment] 2017-01-08 06:12
This looks to me more like an issue with your server.

Could you try this command from the command line to rule out server issues:

```
curl --basic --user <user> "https://<server>/index.php/apps/news/api/v1-2/items?type=3&getRead=false"
```
Replace `<user>` with your username and `<server>` with the url to your server.

**Comment by schaal** [comment] 2017-01-22 09:32
I'm going to close this as there's nothing I can do without further information. Feel free to open it again if you think the issue is with ocreader.

**Closed by schaal** 2017-01-22 09:32 UTC
